import {esc,dayStops} from '../core.js';
const located=p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon);
export function routeMap(plan,day,selectedPlace){
  const all=dayStops(plan,day),ps=all.filter(located),unknown=[...new Map(all.filter(p=>!located(p)).map(p=>[p.id,p])).values()];
  if(!ps.length)return `<h3>当天地点</h3><p>本日无已核实坐标，使用下方地址导航。</p><div class="map-places">${unknown.map(p=>`<button data-place-focus="${esc(p.id)}">${esc(p.name)} · 查看行程</button>`).join('')}</div>`;
  const minX=Math.min(...ps.map(p=>p.lon)),maxX=Math.max(...ps.map(p=>p.lon)),minY=Math.min(...ps.map(p=>p.lat)),maxY=Math.max(...ps.map(p=>p.lat));
  const project=p=>({...p,x:40+(p.lon-minX)/Math.max(maxX-minX,.005)*380,y:35+(maxY-p.lat)/Math.max(maxY-minY,.005)*205});
  const points=ps.map(project),segments=all.slice(1).flatMap((p,i)=>located(p)&&located(all[i])?[[project(all[i]),project(p)]]:[]);
  return `<div class="map-header"><h3>当天路线</h3><span>${new Set(ps.map(p=>p.id)).size} 个有坐标地点</span></div><svg class="route-map" viewBox="0 0 460 280" role="img" aria-label="当天地点经纬度示意，北朝上，点击编号查看行程"><rect width="460" height="280" rx="18" fill="#e8ecdf"/><path d="M0 70H460M0 140H460M0 210H460M115 0V280M230 0V280M345 0V280" stroke="#d6ddcc"/><text x="420" y="22" font-size="12" fill="#47685a">N ↑</text>${segments.map(([a,b])=>`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#74938e" stroke-width="2" stroke-dasharray="5 5"/>`).join('')}${points.map((p,i)=>`<a href="#today" data-place-focus="${esc(p.id)}" aria-label="${esc(p.name)}，查看行程"><circle cx="${p.x}" cy="${p.y}" r="${p.id===selectedPlace?15:11}" fill="${p.id===selectedPlace?'#bb685c':'#47685a'}"/><text x="${p.x}" y="${p.y+4}" fill="white" text-anchor="middle" font-size="11">${i+1}</text></a>`).join('')}</svg><p class="fine">经纬度示意，非道路轨迹；参考点不保证精确入口。未知坐标处断开连线。导航需联网。</p><div class="map-places">${points.map((p,i)=>`<button class="${p.id===selectedPlace?'selected':''}" data-place-focus="${esc(p.id)}">${i+1}. ${esc(p.name)}</button>`).join('')}${unknown.map(p=>`<button data-place-focus="${esc(p.id)}">${esc(p.name)} · 仅地址</button>`).join('')}</div>`;
}
export function overviewRoute(plan){
 const points=plan.cities.map(c=>({...c,...plan.places.find(p=>p.id===c.mapPlaceId),cityId:c.id,cityName:c.name})).filter(located).map(c=>({...c,x:135+(c.lon+6)*29,y:25+(53-c.lat)*20.5}));
 return `<h2>顺着地图，走向海边</h2><div class="geographic-overview"><svg viewBox="0 0 600 380" role="img" aria-label="欧洲五城坐标总览，北朝上"><rect width="600" height="380" rx="18" fill="#e8ecdf"/><path d="M0 86H600M0 188H600M0 291H600M135 0V380M280 0V380M425 0V380" stroke="#cddfdd"/><text x="545" y="25" fill="#47685a" font-size="13">N ↑</text><polyline points="${points.map(p=>p.x+','+p.y).join(' ')}" stroke="#b2825c" stroke-width="2" stroke-dasharray="5 5" fill="none"/>${points.map((p,i)=>`<a href="#today" data-city="${esc(p.cityId)}" aria-label="查看${esc(p.cityName)}"><circle cx="${p.x}" cy="${p.y}" r="9" fill="#47685a"/><text x="${p.x+15}" y="${p.y+5}" fill="#153d4c" font-size="14">${esc(p.cityName.split(' · ')[0])}</text></a>`).join('')}</svg><div class="route-stations">${plan.cities.map((c,i)=>`<button data-city="${esc(c.id)}"><span class="station-dot">${i+1}</span><strong>${esc(c.name)}</strong><small>${esc(c.dates)} · ${c.nights}晚</small></button>`).join('')}</div></div><p class="fine">${esc(plan.meta.route)}<br>欧洲段坐标总览；连线仅示城市顺序，不代表航路、道路或地理边界。机场与国内经停见各日地点。</p>`;
}
