import {esc} from '../core.js';
import {hotelHTML} from './day.js';
import {overviewRoute} from './map.js';

export function cityChapter(plan,id){
  const c=plan.cities.find(c=>c.id===id)||plan.cities[0];
  const days=plan.days.filter(d=>d.chapterId===c.id);
  return `<div class="chapter-intro"><span class="chapter-number">${String(plan.cities.indexOf(c)+1).padStart(2,'0')} / 05</span><h2>${esc(c.headline||c.name)}</h2><p>${esc(c.summary||'')}</p><span class="chapter-location">${esc(c.localName||c.name)}<br>${esc(c.dates)} · ${c.nights} 晚</span></div><div class="chapter-days">${days.map(d=>`<button class="chapter-day" data-day="${d.date}"><time>${d.date.slice(5).replace('-','/')}</time><span><strong>${esc(d.editorial?.headline||d.label)}</strong><small>${esc(d.editorial?.caption||d.label)}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div>`;
}

export function overviewHTML(plan,store,cityId){
  const priority=plan.meta.priorityTaskIds.map(id=>plan.checklist.find(t=>t.id===id)).filter(t=>t&&!store.data.tasks[t.id]);
  const completed=plan.checklist.filter(t=>store.data.tasks[t.id]).length;
  return `<section class="hero"><div class="hero-copy"><p class="eyeline">A JOURNEY FOR TWO · EUROPE 2026</p><h1>从运河，<br>慢慢走到海湾。</h1><p class="hero-sub">建筑、餐桌与散步，<br>还有留给彼此的空白。</p><div class="hero-facts"><span><b>${plan.days.length}</b> 天</span><span><b>${plan.cities.length}</b> 处停留</span><span><b>${plan.hotels.reduce((n,h)=>n+h.nights,0)}</b> 晚</span></div><button class="primary" data-tab="today">打开每日安排 <span>↗</span></button></div><div class="scene-wrap"><div class="scene-kicker">THE LITTLE EUROPE COLLECTION</div><div id="scene-host" role="img" aria-label="欧洲建筑卡通微缩场景，可旋转缩放和点击城市"><img src="./assets/previews/cover.png" alt="欧洲建筑微缩场景静态预览"></div><div class="scene-toolbar"><button id="scene-activate">旋转建筑</button><button id="scene-minus" aria-label="缩小模型">−</button><button id="scene-plus" aria-label="放大模型">＋</button><button id="scene-reset">复位</button></div><p class="scene-caption">点建筑，走进一座城 · 组合位置为艺术示意</p></div></section>
  <section class="journey-chapters"><div class="section-heading inline-heading"><div><span class="eyeline">FIVE CHAPTERS</span><h2>五段旅程，各有自己的节奏</h2></div><span class="fine">09.25 — 10.07</span></div><div class="city-tabs" aria-label="城市章节">${plan.cities.map((c,i)=>`<button data-chapter="${c.id}" aria-pressed="${c.id===cityId}"><span class="city-number">0${i+1}</span><strong>${esc(c.name.split(' · ')[0])}</strong><small>${esc(c.dates)} · ${c.nights}晚</small></button>`).join('')}</div><div class="city-chapter" id="city-chapter">${cityChapter(plan,cityId)}</div></section>
  <section class="ready-section"><div><span class="eyeline">BEFORE WE GO</span><h2>${priority.length?'先把这几件事落定':'优先事项已处理'}</h2><p>已完成 ${completed} / ${plan.checklist.length} 项准备</p><button class="text-button" data-tab="prep">打开准备清单 ↗</button></div><div class="priority-list">${priority.length?priority.map((t,i)=>`<button data-task-jump="${esc(t.id)}"><span>0${i+1}</span><div><strong>${esc(t.item)}</strong><small>${esc(t.date)} · ${t.deadlineType==='actual'?'实际期限':'建议处理'}</small></div><span>↗</span></button>`).join(''):'<p>其余准备与打包状态，可在清单里继续查看。</p>'}</div></section>
  <div class="overview-library"><details><summary>路线地图与城市位置</summary>${overviewRoute(plan)}</details><details><summary>已确认的交通与住宿</summary><div class="transport-list">${plan.legs.filter(l=>l.locked).map(l=>`<article><span>${esc(l.carrier)}</span><strong>${esc(l.departureLocal.replace('T',' '))} → ${esc(l.arrivalLocal.replace('T',' '))}</strong><small>${esc(l.fromTz)} → ${esc(l.toTz)} · 已订已付</small></article>`).join('')}</div><div class="hotel-library">${plan.hotels.map(h=>hotelHTML(plan,{hotelId:h.id})).join('')}</div></details><details><summary>建筑手账 · 沿途的轮廓</summary><div class="brief-grid">${plan.architecture.map(a=>`<article><h3>${esc(plan.cities.find(c=>c.id===a.city)?.name||'海湾白屋')}</h3><p>${a.features.map(esc).join('；')}。</p><p class="fine">卡通原型，非精确地理或工程状态复原。</p></article>`).join('')}</div></details></div>`;
}
