import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {sagrada} from './sagrada.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
function compact(group){group.updateMatrixWorld(true);const inverse=new THREE.Matrix4().copy(group.matrixWorld).invert(),buckets=new Map();group.traverse(o=>{if(o.isMesh){let geo=o.geometry.clone().applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,o.matrixWorld));if(geo.index)geo=geo.toNonIndexed();const arr=buckets.get(o.material)||[];arr.push(geo);buckets.set(o.material,arr);}});group.clear();for(const[m,geos]of buckets){const geo=mergeGeometries(geos);if(!geo)continue;const mesh=new THREE.Mesh(geo,m);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);geos.forEach(x=>x.dispose());}return group;}
export async function createScene(host,onSelect=()=>{},full=false){const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.setClearColor('#f0f1e9',1);host.replaceChildren(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.OrthographicCamera(-8,8,6,-6,.1,100);camera.position.set(12,12,17);const target=new THREE.Vector3(0,2.2,0);camera.lookAt(target);const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.enableDamping=false;controls.enablePan=false;controls.minZoom=.65;controls.maxZoom=2.7;controls.maxPolarAngle=Math.PI/2.15;controls.minPolarAngle=.25;controls.enableZoom=false;controls.enabled=false;
const hemi=new THREE.HemisphereLight('#eff9ff','#c2b48d',1.8);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff2d7',2.5);sun.position.set(-8,15,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:13,bottom:-13,near:1,far:55});sun.shadow.normalBias=.035;scene.add(sun);
const main=compact(sagrada());scene.add(main);const ground=new THREE.Mesh(new THREE.CircleGeometry(7,80),new THREE.MeshStandardMaterial({color:'#e4e9dd',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.35;ground.receiveShadow=true;scene.add(ground);
let extras=[];if(full){const {districts}=await import('./districts.js');extras=districts();extras.forEach(g=>scene.add(compact(g)));main.position.set(.1,0,.25);main.scale.setScalar(.84);ground.scale.set(1.4,1.1,1);camera.position.set(15,16,22);controls.target.set(0,1,0);}
let visible=true;const render=()=>{if(visible)renderer.render(scene,camera);};const resize=()=>{const{width,height}=host.getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height,false);const aspect=width/height,half=Math.max(full?5.6:4.3,(full?9.0:3.6)/aspect);camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();render();};const ro=new ResizeObserver(resize);ro.observe(host);const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible)render();});io.observe(host);controls.addEventListener('change',render);
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects([main,...extras],true)[0];if(hit){let o=hit.object;while(o&&!o.userData.city)o=o.parent;if(o)onSelect(o.userData.city,o.userData.placeId);}});
controls.update();resize();return{renderer,scene,camera,controls,render,activate(value){controls.enabled=value;renderer.domElement.style.touchAction=value?'none':'pan-y';},zoom(delta){camera.zoom=THREE.MathUtils.clamp(camera.zoom+delta,.65,2.7);camera.updateProjectionMatrix();render();},reset(){camera.zoom=1;camera.position.set(...(full?[15,16,22]:[12,12,17]));controls.target.set(0,full?1:2.2,0);controls.update();camera.updateProjectionMatrix();render();},dispose(){ro.disconnect();io.disconnect();controls.dispose();scene.traverse(o=>{if(o.geometry)o.geometry.dispose();});renderer.dispose();}};}
