export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(n);
export function localDate(now,tz){return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function localTime(now,tz){return new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).format(now);}
export function tripZone(plan,now=new Date()){let tz='Asia/Shanghai';for(const l of plan.legs.filter(l=>l.arrivalISO).sort((a,b)=>a.arrivalISO.localeCompare(b.arrivalISO))){if(now>=new Date(l.arrivalISO))tz=l.toTz;}return tz;}
export function todayContext(plan,selected,manual=false,now=new Date()){const tz=tripZone(plan,now),date=localDate(now,tz),inTrip=date>=plan.days[0].date&&date<=plan.days.at(-1).date;const day=plan.days.find(d=>d.date===selected)||plan.days[0];const live=inTrip&&!manual&&date===day.date;const next=live?day.timeline.find(e=>e.enabled!==false&&(!e.endISO||new Date(e.endISO)>now)):null;return{date,tz,day,live,next,phase:date<plan.days[0].date?'before':date>plan.days.at(-1).date?'after':'during'};}
export function budgetRows(plan){const events=plan.days.flatMap(d=>d.timeline).filter(e=>e.enabled!==false);return plan.budget.map(r=>r.activityIds?{...r,eur:r.activityIds.reduce((sum,id)=>{const e=events.find(e=>e.id===id);return e?[sum[0]+(e.costEUR?.[0]||0),sum[1]+(e.costEUR?.[1]||0)]:sum},[0,0])}:r);}
export function totals(plan){const paid=plan.ledger.filter(x=>x.kind==='expense').reduce((s,x)=>s+Math.round(x.amount*100),0)/100;const low=budgetRows(plan).reduce((s,x)=>s+x.eur[0],0)*plan.fx.rate,high=budgetRows(plan).reduce((s,x)=>s+x.eur[1],0)*plan.fx.rate;return{paid,low,high,totalLow:paid+low,totalHigh:paid+high,cash:plan.ledger.filter(x=>x.kind==='cash').reduce((s,x)=>s+x.amount,0)};}
export function activeItems(plan){const enabled=new Set(plan.days.flatMap(d=>d.timeline.filter(e=>e.enabled!==false).map(e=>e.id)));return plan.packing.map(p=>({...p,applicable:!p.activityIds?.length||p.activityIds.some(id=>enabled.has(id))}));}
// Derive map order from active events so deleting a recommendation updates every view.
export function dayStops(plan,day){const stops=[];const add=(id,mode)=>{const p=plan.places.find(p=>p.id===id);if(p&&stops.at(-1)?.id!==id)stops.push({...p,mode:mode||'walk'});};for(const e of day.timeline.filter(e=>e.enabled!==false)){if(e.fromPlaceId)add(e.fromPlaceId,'walk');if(e.endISO?.slice(0,10)<=day.date||!e.endISO)add(e.placeId,e.mode);}return stops;}
export function mapLink(place){return place?.mapUrl||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((place?.localName||place?.name||'')+' '+(place?.address||''));}
export function sourceLinks(plan,ids=[]){return ids.map(id=>plan.sources.find(s=>s.id===id)).filter(Boolean).map(s=>s.url?`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a>`:esc(s.title)).join(' / ');}
export function navigateLink(plan,e){const p=plan.places.find(p=>p.id===e.placeId),from=plan.places.find(p=>p.id===e.fromPlaceId);if(!p)return '';if(e.kind==='hop'&&from&&e.mode!=='fly')return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from.localName+' '+from.address)+'&destination='+encodeURIComponent(p.localName+' '+p.address)+'&travelmode='+(['walk'].includes(e.mode)?'walking':e.mode==='drive'?'driving':'transit');return mapLink(p);}
